# Generated by Django 5.2.5 on 2025-08-15 15:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id_user', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('id_satker', models.CharField(blank=True, max_length=15, null=True)),
                ('nip', models.CharField(max_length=50, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('pangkat', models.CharField(blank=True, max_length=50, null=True)),
                ('jabatan', models.CharField(blank=True, max_length=50, null=True)),
                ('anggota', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('mode_ubah_jabatan', models.BooleanField(default=False)),
                ('mode_purnatugas', models.BooleanField(default=False)),
                ('id_satker_tag', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'indexes': [models.Index(fields=['id', 'created_at'], name='accounts_us_id_4c92fc_idx')],
            },
        ),
    ]
